<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    '@hotwired/stimulus' => [
        'version' => '3.2.2',
    ],
    'olix-backoffice' => [
        'version' => '1.0.6',
    ],
    '@fortawesome/fontawesome-free/css/all.min.css' => [
        'version' => '5.15.4',
        'type' => 'css',
    ],
    'toastr/build/toastr.min.css' => [
        'version' => '2.1.4',
        'type' => 'css',
    ],
    'icheck-bootstrap/icheck-bootstrap.min.css' => [
        'version' => '3.0.1',
        'type' => 'css',
    ],
    'select2/dist/css/select2.min.css' => [
        'version' => '4.0.13',
        'type' => 'css',
    ],
    '@eonasdan/tempus-dominus/dist/css/tempus-dominus.min.css' => [
        'version' => '6.9.4',
        'type' => 'css',
    ],
    'bootstrap4-duallistbox/dist/bootstrap-duallistbox.min.css' => [
        'version' => '4.0.2',
        'type' => 'css',
    ],
    'datatables.net-bs4/css/dataTables.bootstrap4.min.css' => [
        'version' => '1.13.8',
        'type' => 'css',
    ],
    'datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' => [
        'version' => '2.5.0',
        'type' => 'css',
    ],
    'admin-lte/dist/css/adminlte.min.css' => [
        'version' => '3.2.0',
        'type' => 'css',
    ],
    'jquery' => [
        'version' => '3.7.1',
    ],
    'bootstrap/dist/js/bootstrap.bundle.min.js' => [
        'version' => '4.6.2',
    ],
    'admin-lte' => [
        'version' => '3.2.0',
    ],
    'datatables.net' => [
        'version' => '1.13.10',
    ],
    'datatables.net-bs4' => [
        'version' => '1.13.8',
    ],
    'datatables.net-responsive' => [
        'version' => '2.5.0',
    ],
    'datatables.net-responsive-bs4' => [
        'version' => '2.5.0',
    ],
    'bootstrap/js/src/modal.js' => [
        'version' => '4.6.2',
    ],
    'bootstrap4-duallistbox' => [
        'version' => '4.0.2',
    ],
    'bootstrap-switch' => [
        'version' => '3.4.0',
    ],
    '@popperjs/core' => [
        'version' => '2.11.8',
    ],
    '@eonasdan/tempus-dominus' => [
        'version' => '6.9.4',
    ],
    'toastr' => [
        'version' => '2.1.4',
    ],
    'select2/dist/js/select2.full.js' => [
        'version' => '4.0.13',
    ],
    'olix-backoffice/olixbo.min.css' => [
        'version' => '1.0.6',
        'type' => 'css',
    ],
    'tom-select/dist/css/tom-select.default.css' => [
        'version' => '2.3.1',
        'type' => 'css',
    ],
    'tom-select/dist/css/tom-select.bootstrap4.css' => [
        'version' => '2.3.1',
        'type' => 'css',
    ],
    '@symfony/stimulus-bundle' => [
        'path' => './vendor/symfony/stimulus-bundle/assets/dist/loader.js',
    ],
    'tom-select' => [
        'version' => '2.3.1',
    ],
    'chart.js/auto' => [
        'version' => '3.9.1',
    ],
];
